services:
  fina-app:
    build: .
    restart: unless-stopped
    environment:
      - TZ=Asia/Jakarta
      - FLASK_APP=run.py  
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    ports:
      - "5000:5000"
    networks:
      - net-caddy
    volumes:
      - .:/app # Agar perubahan di lokal langsung terbaca container

networks:
  net-caddy:
    external: true

