# app/modules/documents/queries.py

QUERY_PIUTANG = """
    SELECT a.INVOICEDATE AS TANGGAL, a.INVOICENO AS NO_INVOICE, a.SHIPTO1 AS NAMA_CUSTOMER,
           t.NETDAYS AS TERM_PAYMENT, a.INVOICEAMOUNT AS NOMINAL_INV, (a.INVOICEDATE + t.NETDAYS) AS JATUH_TEMPO
    FROM ARINV a LEFT JOIN TERMOPMT t ON a.TERMSID = t.TERMID
    WHERE a.OWING > 0 AND a.INVOICEDATE >= CURRENT_DATE - 30 ORDER BY a.INVOICEDATE ASC
"""

# PERBAIKAN: Menambahkan ASCII_CHAR untuk penomoran alphabet A, B, C pada NO_SO
QUERY_SO = """
    SELECT 
        (c.SONO || ' ' || ASCII_CHAR(64 + (
            SELECT COUNT(*) FROM SODET d2 WHERE d2.SOID = c.SOID AND d2.SEQ <= d.SEQ
        ))) AS NO_SO, 
        c.SODATE AS TANGGAL_SO, d.ITEMNO AS KODE_BARANG, 
        d.ITEMOVDESC AS NAMA_BARANG, d.ITEMRESERVED2 AS PACKING, d.QUANTITY AS QTY
    FROM SO c 
    JOIN SODET d ON c.SOID = d.SOID
    WHERE c.SODATE >= CURRENT_DATE - 20 
    ORDER BY c.SONO ASC, d.SEQ ASC
"""

QUERY_DO = """
    SELECT b.QUANTITY AS QTY, b.ITEMRESERVED2 AS PACKING, b.ITEMNO AS KODE_BARANG,
           b.ITEMOVDESC AS NAMA_BARANG, c.SONO || ' ' || ASCII_CHAR(65 + ( b.SOSEQ )) AS NO_SO,
           a.INVOICEDATE AS TANGGAL_SJ, a.SHIPTO1 AS NAMA_CUSTOMER, a.INVOICENO as NO_SJ
    FROM ARINV a
    JOIN ARINVDET b on a.ARINVOICEID = b.ARINVOICEID
    JOIN SO c on b.SOID = c.SOID
    WHERE a.INVOICEDATE >= current_date - 7 ORDER BY A.INVOICENO ASC
"""

QUERY_FAKTUR = """
    SELECT a.INVOICEDATE AS "Tgl Faktur", e.INVOICENO AS "No. Inv", a.INVOICENO AS "No. SJ",
           a.SHIPTO1 AS "Nama Customer", d.ITEMNO AS "Kode Barang", d.ITEMOVDESC AS "Deskripsi Item",
           d.QUANTITY AS "Kts", d.ITEMUNIT AS "Satuan", d.UNITPRICE AS "Harga Satuan",
           (d.TAXABLEAMOUNT1 + d.TAXABLEAMOUNT2) AS "DPP", (e.TAX1AMOUNT + e.TAX2AMOUNT) AS "PPN",
           d.ITEMDISCPC AS "Disk%", e.INVOICEAMOUNT AS "Total Faktur"
    FROM ARINV a
    JOIN ARINVDET d ON a.ARINVOICEID = d.ARINVOICEID
    LEFT JOIN ARINV e ON d.USEDINSIID = e.ARINVOICEID
    WHERE a.INVOICEDATE >= CURRENT_DATE - 7 ORDER BY a.INVOICENO ASC
"""